name: Node.js CI

on:
  push:
    branches: [main, develop, michael-dev]
  pull_request: #optional
    branches: [main, develop]

defaults:
  run:
    working-directory: ./expressjs-backend

env:
  MONGO_DB: ${{ secrets.MONGO_DB }}
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PWD: ${{ secrets.MONGO_PWD }}
  MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}

jobs:
  build:
    runs-on: ${{ matrix.os }} #ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node-version: [18.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci # similar to npm install
      - run: npm run build --if-present
      - run: npm test
